version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: npgsql_up_fs_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: npgsql_up_fs_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
